export const integrationNotes = {
  coreInputs: {
    tasks: "Array of plain task objects normalized to { id, uniqueId, wbs, name, summary, startDate, endDate }",
    dependencyLinks: "Array of plain dependency objects normalized to { predecessorId, successorId, type, lag, lagFormat }"
  },
  standaloneUiInspiration: [
    "empty right-panel message when no task is selected",
    "selected task card",
    "filtered task list for multi-match name searches",
    "dependency visualization with level 1 and level 2 depth",
    "dependency-card click navigation inside the right panel"
  ],
  officeBoundary: [
    "Read tasks and links through Office.js",
    "Translate Office payloads into core input shapes",
    "Pass normalized data into project-navigator-core",
    "Render results inside the task pane UI"
  ],
  missingForYeomanIntegration: [
    "Generated Office add-in manifest and web asset host files",
    "Office initialization lifecycle from the Yeoman scaffold",
    "Build tooling and local debug wiring for the add-in",
    "Concrete task pane HTML/CSS host page generated by the template"
  ]
};
